# Generated by Django 5.1.4 on 2026-02-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("BACKLOG", "Backlog"),
                    ("TODO", "Todo"),
                    ("IN_PROGRESS", "In Progress"),
                    ("REVIEW", "Review"),
                    ("TESTING", "Testing"),
                    ("DONE", "Done"),
                    ("FAILED", "Failed"),
                ],
                default="TODO",
                max_length=20,
            ),
        ),
    ]
