# Generated by Django 5.1.4 on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_complexity_task_depends_on_task_result_spec_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
