# Generated by Django 5.1.4 on 2026-02-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="color",
            field=models.CharField(blank=True, default="#6366f1", max_length=50),
        ),
    ]
