# Generated by Django 5.1.4 on 2026-02-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_populate_board_memberships"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spec",
            name="odin_id",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
