# Generated by Django 5.1.4 on 2026-02-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_add_executing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcomment",
            name="comment_type",
            field=models.CharField(
                choices=[
                    ("status_update", "Status Update"),
                    ("telemetry", "Telemetry"),
                    ("question", "Question"),
                    ("reply", "Reply"),
                ],
                default="status_update",
                max_length=20,
            ),
        ),
    ]
