# Generated by Django 5.1.4 on 2026-02-23 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0019_add_proof_comment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReflectionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_agent", models.CharField(max_length=50)),
                ("reviewer_model", models.CharField(max_length=100)),
                ("custom_prompt", models.TextField(blank=True, default="")),
                ("context_selections", models.JSONField(default=list)),
                ("requested_by", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("quality_assessment", models.TextField(blank=True, default="")),
                ("slop_detection", models.TextField(blank=True, default="")),
                ("improvements", models.TextField(blank=True, default="")),
                ("agent_optimization", models.TextField(blank=True, default="")),
                ("verdict", models.CharField(blank=True, default="", max_length=20)),
                (
                    "verdict_summary",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("raw_output", models.TextField(blank=True, default="")),
                ("duration_ms", models.BigIntegerField(blank=True, null=True)),
                ("token_usage", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflections",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "reflection_reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
