# Generated by Django 5.1.4 on 2026-02-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0020_reflection_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="reflectionreport",
            name="assembled_prompt",
            field=models.TextField(blank=True, default=""),
        ),
    ]
