# Generated by Django 5.1.4 on 2026-02-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0020_add_summary_comment_type"),
        ("tasks", "0020_task_dates_and_user_role"),
    ]

    operations = []
