# Generated by Django 5.1.4 on 2026-02-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0021_add_assembled_prompt_to_reflection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reflectionreport",
            name="verdict_summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
