# Generated by Django 5.1.4 on 2026-02-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0022_widen_verdict_summary_to_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcomment",
            name="comment_type",
            field=models.CharField(
                choices=[
                    ("status_update", "Status Update"),
                    ("question", "Question"),
                    ("reply", "Reply"),
                    ("proof", "Proof"),
                    ("reflection", "Reflection"),
                ],
                default="status_update",
                max_length=20,
            ),
        ),
    ]
