# Generated by Django 5.1.4 on 2026-02-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0021_merge_20260224_0525"),
        ("tasks", "0023_add_reflection_comment_type"),
    ]

    operations = []
