# Generated by Django 5.1.4 on 2026-02-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0024_merge_20260224_1046"),
    ]

    operations = [
        migrations.AddField(
            model_name="reflectionreport",
            name="execution_trace",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="taskcomment",
            name="comment_type",
            field=models.CharField(
                choices=[
                    ("status_update", "Status Update"),
                    ("question", "Question"),
                    ("reply", "Reply"),
                    ("proof", "Proof"),
                    ("summary", "Summary"),
                    ("reflection", "Reflection"),
                ],
                default="status_update",
                max_length=20,
            ),
        ),
    ]
