# Generated by Django 5.1.4 on 2026-02-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0026_commentattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcomment",
            name="comment_type",
            field=models.CharField(
                choices=[
                    ("status_update", "Status Update"),
                    ("question", "Question"),
                    ("reply", "Reply"),
                    ("proof", "Proof"),
                    ("summary", "Summary"),
                    ("reflection", "Reflection"),
                    ("planning", "Planning"),
                ],
                default="status_update",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SpecComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_email", models.EmailField(max_length=254)),
                ("author_label", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField()),
                ("attachments", models.JSONField(blank=True, default=list)),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("status_update", "Status Update"),
                            ("question", "Question"),
                            ("reply", "Reply"),
                            ("proof", "Proof"),
                            ("summary", "Summary"),
                            ("reflection", "Reflection"),
                            ("planning", "Planning"),
                        ],
                        default="status_update",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.spec",
                    ),
                ),
            ],
            options={
                "db_table": "spec_comments",
                "ordering": ["created_at"],
            },
        ),
    ]
