# Generated by Django 5.1.4 on 2026-02-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0027_spec_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="reflectionreport",
            name="quota_failure",
            field=models.TextField(blank=True, default=""),
        ),
    ]
