# Generated by Django 5.1.4 on 2026-02-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_task_kanban_position'),
        ('tasks', '0028_add_quota_failure_to_reflection'),
    ]

    operations = [
    ]
