# Generated by Django 5.1.4 on 2026-02-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0029_merge_20260228_0745"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="odin_initialized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="board",
            name="working_dir",
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
