# Generated by Django 5.1.4 on 2026-03-13 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_agent_routing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ONE_TIME', 'One Time'), ('RECURRING', 'Recurring')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('timezone', models.CharField(max_length=64)),
                ('template_title', models.CharField(max_length=255)),
                ('template_description', models.TextField(blank=True, default='')),
                ('template_priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('template_model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template_label_ids', models.JSONField(blank=True, default=list)),
                ('template_depends_on', models.JSONField(blank=True, default=list)),
                ('template_dev_eta_seconds', models.BigIntegerField(blank=True, null=True)),
                ('template_metadata', models.JSONField(blank=True, default=dict)),
                ('starts_at_local', models.DateTimeField()),
                ('starts_at_utc', models.DateTimeField()),
                ('next_run_at_utc', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recurrence_rule', models.JSONField(blank=True, default=dict)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tasks.board')),
                ('materialized_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_schedule', to='tasks.task')),
                ('template_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='tasks.user')),
                ('template_spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='tasks.spec')),
            ],
            options={
                'db_table': 'task_schedules',
                'ordering': ['next_run_at_utc', 'id'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialized_tasks', to='tasks.taskschedule'),
        ),
        migrations.CreateModel(
            name='TaskScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.IntegerField(default=1)),
                ('scheduled_for_utc', models.DateTimeField(db_index=True)),
                ('released_at_utc', models.DateTimeField(blank=True, null=True)),
                ('finished_at_utc', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_RELEASE', 'Pending Release'), ('RELEASED', 'Released'), ('SKIPPED_OVERLAP', 'Skipped Overlap'), ('COMPLETED_SUCCESS', 'Completed Success'), ('COMPLETED_FAILED', 'Completed Failed'), ('CANCELED', 'Canceled')], default='PENDING_RELEASE', max_length=32)),
                ('terminal_task_status', models.CharField(blank=True, choices=[('BACKLOG', 'Backlog'), ('TODO', 'Todo'), ('IN_PROGRESS', 'In Progress'), ('EXECUTING', 'Executing'), ('REVIEW', 'Review'), ('TESTING', 'Testing'), ('DONE', 'Done'), ('FAILED', 'Failed')], max_length=20, null=True)),
                ('release_reason', models.TextField(blank=True, default='')),
                ('result_summary', models.TextField(blank=True, default='')),
                ('template_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tasks.taskschedule')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_runs', to='tasks.task')),
            ],
            options={
                'db_table': 'task_schedule_runs',
                'ordering': ['-scheduled_for_utc', '-id'],
            },
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='last_released_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.taskschedulerun'),
        ),
        migrations.AddField(
            model_name='task',
            name='current_schedule_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_tasks', to='tasks.taskschedulerun'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='schedule_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='tasks.taskschedulerun'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='schedule_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='tasks.taskschedulerun'),
        ),
        migrations.AddConstraint(
            model_name='taskschedulerun',
            constraint=models.UniqueConstraint(fields=('schedule', 'scheduled_for_utc'), name='uniq_schedule_occurrence'),
        ),
    ]
