# Generated by Django 5.1.4 on 2026-03-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_agent_routing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='planner_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='spec',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('planning_complete', 'Planning Complete'), ('active', 'Active')], default='active', max_length=32),
        ),
    ]
