# Generated by Django 5.1.4 on 2026-03-20 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_remove_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='tasks.board'),
        ),
    ]
