# Generated by Django 5.1.4 on 2026-03-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_spec_status_planner_config'),
        ('tasks', '0033_remove_pushsubscription'),
    ]

    operations = [
    ]
