# Generated by Django 5.1.4 on 2026-03-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_board_timezone_taskschedule_task_schedule_and_more'),
        ('tasks', '0033_remove_pushsubscription'),
    ]

    operations = [
    ]
