# Generated by Django 5.1.4 on 2026-03-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_merge_20260317_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('planning_complete', 'Planning Complete'), ('planning_failed', 'Planning Failed'), ('active', 'Active')], default='active', max_length=32),
        ),
    ]
