# Generated by Django 5.1.4 on 2026-03-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_merge_20260324_0756'),
        ('tasks', '0035_board_reflection_settings'),
    ]

    operations = [
    ]
