# Generated by Django 5.1.4 on 2026-03-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_label_board'),
        ('tasks', '0036_merge_20260324_1519'),
    ]

    operations = [
    ]
