# Generated by Django 5.1.4 on 2026-03-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_usersetting'),
        ('tasks', '0037_merge_0034_label_board_0036_merge_20260324_1519'),
    ]

    operations = [
    ]
