# Generated by Django 5.1.4 on 2026-03-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_alter_spec_status'),
        ('tasks', '0038_merge_20260325_1044'),
    ]

    operations = [
    ]
