# Generated by Django 5.1.4 on 2026-04-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_board_skip_proof'),
        ('tasks', '0039_merge_0035_alter_spec_status_0038_merge_20260325_1044'),
    ]

    operations = [
    ]
