# Generated by Django 5.1.5 on 2026-04-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_board_skip_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='model_escalation_priority',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
