# Generated by Django 5.1.5 on 2026-04-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_board_model_escalation_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='failure_max_retries',
            field=models.IntegerField(default=3),
        ),
    ]
