# Generated by Django 5.1.5 on 2026-04-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_board_failure_max_retries'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='escalation_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
