# Generated by Django 5.1.4 on 2026-04-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_merge_20260406_0719'),
        ('tasks', '0042_board_escalation_enabled'),
    ]

    operations = [
    ]
