# Generated by Django 5.1.4 on 2026-05-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_merge_20260407_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='auto_start_planned_tasks',
            field=models.BooleanField(default=False),
        ),
    ]
