# Generated by Django 5.1.4 on 2026-07-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0045_board_allow_project_root_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False for agent Users retired from agent_models.json (seedmodels prune). The User record is preserved so historical tasks/comments still resolve FK references; routing/UI queries filter on this.'),
        ),
    ]
