# Generated by Django 5.1.4 on 2026-07-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0049_board_metadata'),
        ('tasks', '0049_task_status_canceled'),
    ]

    operations = [
    ]
