# Generated by Django 5.1.4 on 2026-07-07 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0050_merge_0049_board_metadata_0049_task_status_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('sandbox_name', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(choices=[('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('EXPIRED', 'Expired'), ('KILLED', 'Killed')], db_index=True, default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='tasks.spec')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tasks.task')),
            ],
            options={
                'db_table': 'task_runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
