# Generated by Django 5.1.4 on 2026-07-07 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0051_taskrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('reflection_pass', 'Reflection Pass'), ('retry', 'Retry'), ('human_resume', 'Human Resume')], max_length=20)),
                ('mode', models.CharField(choices=[('static', 'Static'), ('agent', 'Agent'), ('human_assisted', 'Human Assisted')], max_length=20)),
                ('outcome', models.CharField(choices=[('merged', 'Merged'), ('conflict', 'Conflict'), ('error', 'Error')], max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('conflicting_files', models.JSONField(blank=True, default=list)),
                ('agent_model', models.CharField(blank=True, default='', max_length=100)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_attempts', to='tasks.spec')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_attempts', to='tasks.task')),
            ],
            options={
                'db_table': 'merge_attempts',
                'ordering': ['-started_at'],
            },
        ),
    ]
