# Generated by Django 5.1.4 on 2026-07-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0059_errorevent_comment_attribution_loss"),
        ("tasks", "0060_errorevent_seed_task249"),
    ]

    operations = []
