# Generated by Django 5.1.4 on 2026-07-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0059_errorevent_error_loop"),
        ("tasks", "0061_merge_20260708_1410"),
    ]

    operations = []
