# Generated by Django 5.1.4 on 2026-07-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0062_merge_20260708_1739"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="reviewer_order",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Deterministic, quota-aware reflection reviewer walk. Ordered list of {agent_name, model_name}; index 0 is tried first. Replaces the old random default-reviewer pick. Empty list falls back to a deterministic strongest-first ordering derived from the board's enabled agents.",
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Board-level feature flags. Wave 4: {"auto_promote_enabled": false} disables auto-promotion for this board. Absent or true (default) keeps the feature on.',
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="reflection_review_strategy",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="W3.18 size-bucketed reviewer selection. Empty/unset preserves the single-reviewer default. Set to a dict of {small, medium, large} → model name to scale reviewer choice by review context size, e.g. {'small': 'claude-haiku-4-5', 'medium': 'claude-sonnet-4-6', 'large': 'claude-sonnet-4-6'}. Optional 'thresholds' key overrides the default bucket sizes (small_max, large_min).",
            ),
        ),
        migrations.AlterField(
            model_name="errorevent",
            name="source",
            field=models.CharField(
                choices=[
                    ("failure_tagger", "Failure tagger miss"),
                    ("merge_failure", "Merge ladder failure"),
                    ("reflection_error", "Reflection ERROR verdict"),
                    ("gate_crash", "Spec-verify gate crash"),
                    ("celery_exception", "Celery task exception"),
                    (
                        "agent_malformed_status",
                        "Agent emitted malformed ODIN-STATUS block",
                    ),
                    ("reflection_no_reviewer", "Reflection no reviewer available"),
                    (
                        "comment_attribution_loss",
                        "Comment attributed to unknown@user (attribution lost)",
                    ),
                    (
                        "reflect_param_ignored",
                        "Reflect endpoint ignored explicit reviewer",
                    ),
                    ("error_loop", "Run reconciler error-loop detection"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="taskschedulerun",
            name="terminal_task_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BACKLOG", "Backlog"),
                    ("TODO", "Todo"),
                    ("IN_PROGRESS", "In Progress"),
                    ("EXECUTING", "Executing"),
                    ("REVIEW", "Review"),
                    ("TESTING", "Testing"),
                    ("DONE", "Done"),
                    ("FAILED", "Failed"),
                    ("CANCELED", "Canceled"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
