# Generated by Django 5.1.4 on 2026-07-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0045_system_setting"),
        ("tasks", "0063_board_reviewer_order_alter_board_metadata_and_more"),
    ]

    operations = []
