# Generated by Django 5.1.4 on 2026-07-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0064_merge_20260709_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='routing_policy',
            field=models.JSONField(blank=True, default=dict, help_text="Per-board routing policy (task #328). The single, editable override layer over the built-in per-failure-class routing table (tasks.failure_policy.DEFAULT_POLICY_TABLE). Empty dict (default) means 'use the built-in defaults' — Default First. Recognised keys: 'preference_order' (ordered agent names used when routing a protocol/infra failure to a same-tier peer — e.g. ['glm','minimax','agy','codex','claude']); 'failure_actions' (per-failure-class {action, max_retries} overrides); 'capability_escalate_after' (int: number of review rejections before a deliberate one-tier escalation). Changes take effect on the next dispatch with no restart."),
        ),
    ]
