# Generated by Django 5.1.4 on 2026-07-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0065_board_routing_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_assigned", "Task Assigned"),
                    ("comment_added", "Comment Added"),
                    ("status_changed", "Status Changed"),
                    ("planning_complete", "Planning Complete"),
                    ("question_asked", "Question Asked"),
                    ("spec_finished", "Spec Finished"),
                    ("task_failed", "Task Failed"),
                    ("task_failed_reminder", "Task Failed Reminder"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
