"""Git worktree isolation for parallel task execution.

Each spec gets a branch (spec/<spec_id>) forked from main.
Each task gets a worktree with its own branch (task/<spec_id>/<task_id>)
forked from the spec branch. On task completion, the task branch is
merged back into the spec branch. On spec completion, a PR is created.

All git operations are serialized per-spec via file locks to prevent
concurrent merge races.
"""

import logging
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from odin.mcps.taskit_mcp.config import HARNESS_GENERATED_PATHS

logger = logging.getLogger("odin.worktree")

# Source paths (in project_root) copied into each worktree so agent CLIs
# find their settings.  Derived from the harness-generated paths plus
# odin's own project-level config files (``.env``, ``.odin/config.yaml``).
AGENT_CONFIG_PATHS = (
    *HARNESS_GENERATED_PATHS,
    ".odin/config.yaml",
    ".env",
)

# Worktree-local runtime paths that odin writes but should never commit
# (logs, costs, locks, specs).  These are NOT generated by harness/MCP
# config writers, so they're tracked separately from HARNESS_GENERATED_PATHS.
_WORKTREE_LOCAL_PATHS = (
    ".env",
    ".odin",
    ".proof",
)

# Defensive gitignore-only patterns for retired agents whose configs may
# still exist on disk from old worktrees (e.g. ``.qwen/`` after task #102
# retired qwen).  These are NOT included in the auto-commit reset or the
# untracked-config cleanup — those operate only on paths that live config
# writers actually produce.  Stray legacy artifacts are kept out of
# commits purely via the worktree ``.gitignore``.
_LEGACY_GITIGNORE_PATHS = (
    ".qwen",
)

# Backwards-compatible union (kept for tests / external callers).
_WORKTREE_GITIGNORE_PATHS = (
    *HARNESS_GENERATED_PATHS,
    *_WORKTREE_LOCAL_PATHS,
    *_LEGACY_GITIGNORE_PATHS,
)

_GITIGNORE_MARKER = "# odin-worktree-agent-configs"


def _provenance_trailers(spec_id: str, task_id: str) -> str:
    """Build the ``Task-Id``/``Spec-Id`` trailer block appended to every
    commit odin creates on the merge path (auto-commit + merge commit).

    The blank-line separator + ``Key: value`` lines at the end of the
    message are recognized by ``git interpret-trailers`` and
    ``git log --format=%(trailers:key=...)`` — this is what
    ``testing_tools/why.py`` walks to answer "why does this line exist".
    """
    return f"\n\nTask-Id: {task_id}\nSpec-Id: {spec_id}"

# ---------------------------------------------------------------------------
# Defence-in-depth against merge-time auto-commit pollution
# ---------------------------------------------------------------------------
# A stale worktree ``.gitignore`` (one missing ``.venv*/`` etc.) lets
# ``git add -A`` sweep an entire venv / node_modules tree into the task
# branch — a single such incident dragged 4,738 files (1.2M lines) through
# every later merge.  The guards below catch pollution that ``.gitignore``
# misses, because correctness here cannot depend on an ignore file that
# may predate the pollution it is supposed to exclude.

# Path *components* (directory names, matched at any depth) that are
# always build/runtime pollution — never legitimate source.
_POLLUTION_COMPONENTS = frozenset({
    "node_modules",
    "site-packages",
    "__pycache__",
})

# Directory-name prefixes/exacts that mark a Python virtual environment
# (``.venv``, ``.venv311``, ``venv``).  Matched as path components.
_VENV_COMPONENT_PREFIXES = (".venv",)
_VENV_COMPONENT_EXACT = frozenset({"venv"})

# The definitive venv root marker.  If ``pyvenv.cfg`` appears anywhere in
# the staged tree, its parent directory is a venv and the whole subtree
# is excluded — this catches venvs at non-standard names (``env/``).
_VENV_MARKER_FILE = "pyvenv.cfg"

# Bulk-add guard: if the auto-commit would stage more than this many NEW
# (previously untracked) files, refuse the bulk and commit only tracked
# modifications.  Catches pollution classes the blocklist doesn't name yet.
_AUTO_COMMIT_MAX_NEW_FILES = 200

# Batch size for ``git reset -- <paths>`` calls, to stay well under the
# OS ARG_MAX limit when unstaging thousands of pollution files.
_RESET_BATCH_SIZE = 500


def _find_venv_roots(staged_paths):
    """Return the set of venv root directories detected via the
    ``pyvenv.cfg`` marker file among ``staged_paths``.

    A venv is a directory containing ``pyvenv.cfg``; its root is the
    marker's parent.  This catches venvs whose name doesn't match the
    ``.venv*`` / ``venv`` component patterns (e.g. ``env/``).
    """
    roots = set()
    for p in staged_paths:
        if p.endswith("/" + _VENV_MARKER_FILE):
            roots.add(p[: -(len(_VENV_MARKER_FILE) + 1)])
    return frozenset(roots)


def _is_pollution_path(path, venv_roots):
    """True if ``path`` is venv/build pollution that must never be
    committed, regardless of ``.gitignore`` state.

    Matching is by path *component* so pollution at any depth is caught
    (``src/foo/node_modules/x``, ``.venv/bin/python``).  Venv roots
    detected via ``pyvenv.cfg`` cover non-standard venv names.
    """
    for part in path.split("/"):
        if part in _POLLUTION_COMPONENTS or part in _VENV_COMPONENT_EXACT:
            return True
        if part.startswith(_VENV_COMPONENT_PREFIXES):
            return True
    for root in venv_roots:
        if path == root or path.startswith(root + "/"):
            return True
    return False


@dataclass
class MergeResult:
    success: bool
    conflict: bool = False
    noop: bool = False
    error: Optional[str] = None
    diff_stat: Optional[str] = None
    conflicting_files: List[str] = field(default_factory=list)
    resolved_files: List[str] = field(default_factory=list)
    ambiguous_files: List[str] = field(default_factory=list)
    resolution_rationale: Optional[str] = None
    needs_human: bool = False
    # True when the failure is a Django migration leaf collision (W5.3).
    # Lets ``dag_executor`` route the parking comment through the
    # migration formatter (leaves + renumber/merge-migration options)
    # instead of the merge-agent's content-conflict formatter.  Only set
    # on the fallback path: the gate auto-runs ``makemigrations --merge``
    # first, so this flag surfaces only when the auto-fix itself failed.
    migration_conflict: bool = False
    # Per-file conflict context captured before the merge is aborted so
    # downstream callers (``dag_executor``) can render a self-contained
    # report without re-running git.  Maps file path → first conflict
    # region as written by git (with ``<<<<<<<`` markers).
    conflict_hunks: Dict[str, str] = field(default_factory=dict)
    # Per-file verdict and rationale (``{"verdict": "choose", "rationale": "..."}``)
    # — produced by :func:`odin.merge_agent.classify_resolution`.  Lets
    # the report suggest ``keep-both`` vs ``choose`` inline.
    file_resolutions: Dict[str, Dict[str, str]] = field(default_factory=dict)
    # Per-file commit subject lines explaining WHY each side touched the
    # file (spec side from ``HEAD``, task side from ``MERGE_HEAD``) —
    # see :func:`odin.merge_agent._commit_subjects_for_path`.
    spec_commit_messages: Dict[str, List[str]] = field(default_factory=dict)
    task_commit_messages: Dict[str, List[str]] = field(default_factory=dict)
    # Model + token usage when the merge agent's resolution step invoked an
    # LLM (task #209) — empty for the deterministic rule-based path used
    # today. Mirrors ReflectionReport.token_usage so cost is derived the
    # same way, not stored twice.
    agent_model: Optional[str] = None
    token_usage: Dict[str, int] = field(default_factory=dict)
    # Post-merge safety gate (task 338) violations: list of
    # ``(path, error_type, line_no)`` for files the gate flagged after
    # the merge commit landed. Empty when the merge is clean. When
    # non-empty, the merge commit has been rolled back via
    # ``git reset --hard HEAD~1`` so the spec branch is unchanged;
    # callers surface the violations through the merge question /
    # parking comment. ``error_type`` is one of ``"conflict_marker"``
    # or ``"syntax_error"``.
    gate_violations: List[Tuple[str, str, int]] = field(default_factory=list)


@dataclass
class AutoCommitResult:
    """Outcome of a merge-time auto-commit.

    Carries the defence-in-depth exclusion counts so callers (and tests)
    can surface that pollution was refused — never silently.  Truthy iff
    a commit was created, preserving the legacy ``bool`` contract of
    :meth:`WorktreeManager._auto_commit_worktree`.

    Attributes:
        committed: True if a commit was created.
        skipped_blocklist: number of staged files excluded by the
            pollution blocklist (venv / node_modules / __pycache__ …).
        skipped_bulk: number of staged NEW files excluded by the
            bulk-add guard (over ``_AUTO_COMMIT_MAX_NEW_FILES``).
    """
    committed: bool = False
    skipped_blocklist: int = 0
    skipped_bulk: int = 0

    def __bool__(self) -> bool:
        return self.committed

    @property
    def skipped(self) -> int:
        return self.skipped_blocklist + self.skipped_bulk

    @property
    def summary(self) -> str:
        if not self.skipped:
            return ""
        parts = []
        if self.skipped_blocklist:
            parts.append(
                f"{self.skipped_blocklist} pollution-blocklisted "
                f"(venv/node_modules/__pycache__)"
            )
        if self.skipped_bulk:
            parts.append(
                f"{self.skipped_bulk} bulk-guarded "
                f"(over {_AUTO_COMMIT_MAX_NEW_FILES} new files)"
            )
        return "Auto-commit excluded: " + "; ".join(parts)


# Two-letter porcelain status prefixes that indicate an unresolved
# merge conflict.  ``UU`` = both modified, ``AA`` = both added,
# ``DD`` = both deleted, ``UD``/``DU`` = modify-vs-delete, ``AU``/``UA``
# = rename/add family.  The delete/rename family was previously excluded
# on the theory git auto-resolves it — task 284 disproved that live: a
# modify/delete conflict aborted the merge with an EMPTY error and no
# needs_human question, parking the task silently for hours.  Every
# unmerged state now feeds the same conflict machinery.
_CONFLICT_STATUS_PREFIXES = ("UU", "AA", "DD", "UD", "DU", "AU", "UA")


def _extract_conflicting_files(porcelain_lines: List[str]) -> List[str]:
    """Return the file paths from ``git status --porcelain`` that are
    in a conflict state (UU/AA/DD prefixes).  Untracked (``??``) and
    staged-but-clean entries are intentionally excluded — only files
    blocking the merge are surfaced so downstream status comments stay
    actionable.
    """
    files: List[str] = []
    for line in porcelain_lines:
        if not line or len(line) < 4:
            continue
        prefix = line[:2]
        if prefix not in _CONFLICT_STATUS_PREFIXES:
            continue
        # Porcelain format: "<XY> <path>" with the path starting at
        # column 3. Rename entries ("XY <old> -> <new>") would need
        # extra parsing, but rename conflicts are rare in this flow
        # and `update_conflict_info` shows them too.
        path = line[3:].strip()
        if path:
            files.append(path)
    return files


# ---------------------------------------------------------------------------
# Django migration leaf-conflict detection
# ---------------------------------------------------------------------------
#
# When two parallel task branches each mint a migration under the same
# numeric prefix (``0049_board_metadata`` and ``0049_task_status_canceled``
# were the wave-4 case), ``git merge --no-ff`` lands them side-by-side in
# the spec branch tree.  Git sees no overlap and the merge succeeds — but
# the migration graph now has two leaves with no merge migration tying them
# together.  Every sibling branch's backend suite then dies on
# ``CommandError: Conflicting migrations detected`` until a human hand-adds
# a ``0050_merge_0049_*.py`` migration.
#
# The fix belongs on the merge path: detect the conflict BEFORE the broken
# state is pushed to the spec branch, name the two leaves so the operator
# knows exactly what to renumber / merge, and abort the local merge commit
# (the spec branch stays clean — humans stay in charge of resolution).
#
# Reference: ``taskit/taskit-backend/tasks/migrations/`` is the canonical
# Django app checked on the merge path.  The check is generic enough to
# skip silently for repos without a TaskIt backend (``worktree.py`` is
# used by every project odin orchestrates, not just TaskIt).


@dataclass
class MigrationConflictCheck:
    """Structured result of a Django migration leaf-conflict check.

    ``has_conflict`` is the single signal callers need to decide
    whether to abort a merge.  ``leaves`` and ``app`` are populated
    only when Django reported a leaf collision; they feed the
    operator-facing message that names the offending files.
    """

    has_conflict: bool = False
    leaves: List[str] = field(default_factory=list)
    app: Optional[str] = None


# Django's error line looks like:
#   Conflicting migrations detected; multiple leaf nodes in the migration
#   graph: (0049_a, 0049_b in tasks).
# The leaf filenames are alphanumeric+underscore; the app follows ``in``
# inside the same parenthetical.  We pull leaves and app out of the same
# match so a single regex covers the format Django has shipped across 4.x
# and 5.x — see Django's ``django.db.migrations.loader`` for the source.
_CONFLICT_LEAVES_RE = __import__("re").compile(
    r"multiple leaf nodes in the migration graph:\s*\(([^)]+)\)"
)


def _parse_conflict_leaves(stderr: str) -> MigrationConflictCheck:
    """Extract the colliding leaf filenames and owning app from
    Django's ``makemigrations`` stderr.

    Returns ``MigrationConflictCheck(has_conflict=False, ...)`` when
    the message is absent or unparseable — callers must treat a
    non-conflict Django error (e.g. model drift) as ``has_conflict=False``
    so the merge path doesn't mistake it for a leaf collision (the
    operator fix is completely different: add a migration, not merge).

    The parser is defensive by design: it never raises on weird input.
    A successful parse produces ``has_conflict=True`` with the leaves
    and app populated; anything else produces ``has_conflict=False``.
    """
    import re

    if not stderr:
        return MigrationConflictCheck()

    match = _CONFLICT_LEAVES_RE.search(stderr)
    if not match:
        return MigrationConflictCheck()

    inner = match.group(1)
    # Split leaves on ``, `` then strip the trailing ``in <app>`` from
    # the last leaf.  Each leaf token is the bare migration filename
    # (no extension); the app token follows ``in`` at the end of the
    # parenthetical and is excluded from the leaf list.
    raw_tokens = [t.strip() for t in inner.split(",") if t.strip()]
    app: Optional[str] = None
    leaves: List[str] = []
    for token in raw_tokens:
        m = re.match(r"^(\S+)\s+in\s+(\S+)$", token)
        if m:
            leaves.append(m.group(1))
            app = m.group(2)
        else:
            leaves.append(token)

    if not leaves:
        return MigrationConflictCheck()

    return MigrationConflictCheck(has_conflict=True, leaves=leaves, app=app)


# Path to the Django backend inside the worktree, relative to the project
# root.  Centralised so the locator can evolve (e.g. env override, config)
# without touching every caller.
_DJANGO_BACKEND_REL_PATH = Path("taskit") / "taskit-backend"


def _check_django_migration_conflicts(worktree_path: Path) -> MigrationConflictCheck:
    """Run ``python manage.py makemigrations --check --dry-run`` inside
    the worktree's Django backend and parse the result.

    ``makemigrations --check --dry-run`` is the standard Django idiom
    for CI: it exits non-zero when there are *uncommitted model
    changes*, but — critically — it ALSO exits non-zero when the
    migration graph has multiple leaf nodes.  We use that second case
    to detect the wave-4 collision class.

    Behaviour:
      * No Django backend on disk → return ``has_conflict=False``
        (skip the check — worktrees for non-TaskIt projects don't
        have a backend, and forcing a Django check there would be a
        false positive).
      * Django exits 0 → ``has_conflict=False``.
      * Django exits 1 with ``Conflicting migrations detected`` in
        stderr → ``has_conflict=True`` with leaves parsed.
      * Django exits 1 for any OTHER reason (model drift,
        ImportError, missing apps) → ``has_conflict=False``.  The
        caller surfaces those errors separately; mistaking drift
        for a leaf collision would block every merge with a wrong
        fix message.
      * Subprocess raises (e.g. python3 not found, OOM, timeout) →
        ``has_conflict=False`` with a logged warning.  Better to
        let the merge proceed and surface the real Django error
        downstream than to block every merge because the check
        itself blew up.
    """
    backend = worktree_path / _DJANGO_BACKEND_REL_PATH
    if not (backend / "manage.py").is_file():
        return MigrationConflictCheck()

    try:
        result = subprocess.run(
            ["python3", "manage.py", "makemigrations", "--check", "--dry-run"],
            cwd=str(backend),
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        # Conservative: never block a merge on a failed *check*.  The
        # Django error itself will surface when the next test suite
        # runs against the worktree, which is the right place for it.
        logger.warning(
            "Django migration conflict check failed to run in %s: %s",
            backend, exc,
        )
        return MigrationConflictCheck()

    if result.returncode == 0:
        return MigrationConflictCheck()

    parsed = _parse_conflict_leaves(result.stderr or "")
    if not parsed.has_conflict:
        # Non-zero exit for a NON-leaf-collision reason (e.g. model
        # drift).  Return clean so the merge path doesn't mistake it
        # for the wave-4 case.
        return MigrationConflictCheck()

    logger.warning(
        "Migration leaf collision detected in %s: leaves=%s app=%s",
        backend, parsed.leaves, parsed.app,
    )
    return parsed


def _format_migration_conflict_error(
    leaves: List[str],
    app: Optional[str],
) -> str:
    """Build the operator-facing error message for a leaf collision.

    Two leaves minimum (Django's ``makemigrations`` requires at least
    two to fire), but the format accommodates more (the parser returns
    a list of arbitrary length).  The message names every leaf AND
    tells the operator how to fix it — renumber one leaf or commit a
    merge migration — so a glance at the board comment is enough to
    unblock.

    The message is also the canonical copy for the
    :class:`MergeResult.error` field, which downstream code posts to
    the TaskIt board as a status comment.
    """
    app_label = app or "the migration graph"
    leaf_list = ", ".join(leaves)
    return (
        f"Django migration leaf collision in {app_label}: "
        f"{len(leaves)} leaves with no merge migration — {leaf_list}. "
        f"Fix: (1) renumber one of the leaves so they don't share a "
        f"migration prefix, or (2) commit a merge migration via "
        f"`python3 manage.py makemigrations --merge` inside "
        f"taskit/taskit-backend/ before retrying the merge."
    )


def _is_generated_agent_config(path: str) -> bool:
    """True if ``path`` matches any pattern the harness/MCP config
    writers produce (single source of truth lives in
    ``HARNESS_GENERATED_PATHS``).

    Patterns come in two flavours:

    - **Glob patterns** with ``*``, ``?`` etc. (``*.orig``) —
      matched literally with ``fnmatch``.
    - **Directory prefixes** like ``.claude`` — match any path under
      that directory.  Detected by absence of a glob character.

    The dual handling is intentional: glob patterns are evaluated by
    ``fnmatch`` to honour their semantics, while plain directory names
    (which are how the harness writers declare the *root* of an agent's
    config subtree) match by simple ``startswith``.
    """
    import fnmatch

    for pattern in HARNESS_GENERATED_PATHS:
        if any(ch in pattern for ch in ("*", "?", "[")):
            if fnmatch.fnmatch(path, pattern):
                return True
        else:
            needle = pattern if pattern.endswith(("/", "")) else pattern + "/"
            other = path if path.endswith(("/", "")) else path + "/"
            if other.startswith(needle) or path == pattern.rstrip("/"):
                return True
    return False


def format_merge_conflict_comment(
    branch: str,
    spec_branch: str,
    conflicting_files: List[str],
) -> str:
    """Format the operator-facing status comment for a merge conflict.

    Includes the conflicting file list so the board UI is self-explanatory
    (regression for task #112: a bare ``"Merge conflict:"`` line left the
    operator with no UI affordance to debug).  When any conflicting file
    matches a known generated agent config (see ``HARNESS_GENERATED_PATHS``
    — e.g. ``opencode.json``, ``.mcp.json``), a one-line hint is added
    pointing at F24 for safe resolution.  The hint is intentionally
    greppable so dashboards can flag the common case.
    """
    lines = [f"Merge conflict merging `{branch}` into `{spec_branch}`:"]
    if conflicting_files:
        lines.append("")
        lines.append("Conflicting files:")
        for path in conflicting_files:
            lines.append(f"- `{path}`")
        generated = [p for p in conflicting_files if _is_generated_agent_config(p)]
        if generated:
            lines.append("")
            lines.append(
                "Hint: at least one conflicting file is a generated agent "
                "config (see F24) — these files are rewritten on every "
                "task run and frequently collide. See `odin worktree show` "
                "for safe resolution."
            )
    return "\n".join(lines)


class WorktreeManager:
    """Manages git worktrees for spec/task isolation.

    Single owner of all git commands related to worktree lifecycle.
    All operations are idempotent — safe to retry on failure.
    """

    def __init__(
        self,
        project_root: Path,
        worktree_dir: str = ".odin/worktrees",
    ):
        self.project_root = Path(project_root).resolve()
        if not (self.project_root / ".git").exists():
            raise ValueError(f"Not a git repository: {self.project_root}")
        self.worktree_base = self.project_root / worktree_dir
        self.lock_dir = self.project_root / ".odin" / "locks"

    def _git(self, *args: str, cwd: Optional[Path] = None) -> subprocess.CompletedProcess:
        """Run a git command, logging the invocation."""
        cmd = ["git"] + list(args)
        work_dir = cwd or self.project_root
        logger.debug("git %s (cwd=%s)", " ".join(args), work_dir)
        result = subprocess.run(
            cmd,
            cwd=work_dir,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode != 0:
            logger.debug("git exit=%d stderr=%s", result.returncode, result.stderr.strip())
        return result

    def _branch_exists(self, branch: str) -> bool:
        """Check if a local branch exists."""
        result = self._git("rev-parse", "--verify", f"refs/heads/{branch}")
        return result.returncode == 0

    def is_task_merged(self, spec_id: str, task_id: str) -> bool:
        """Return True if the task branch is already merged into the spec branch.

        Uses ``git merge-base --is-ancestor``: the task branch is merged when
        it is reachable as an ancestor of the spec branch tip. This is the
        git-reality check the merge watchdog uses to avoid escalating a merge
        whose commit landed but whose metadata stamp never did (e.g. the
        celery worker died after the merge commit).

        Returns False when either branch is missing so callers can treat
        'unknown / not yet merged' uniformly — never raises.
        """
        spec_branch = f"spec/{spec_id}"
        task_branch = f"task/{spec_id}/{task_id}"
        if not self._branch_exists(spec_branch) or not self._branch_exists(task_branch):
            return False
        result = self._git("merge-base", "--is-ancestor", task_branch, spec_branch)
        return result.returncode == 0

    def is_ancestor(self, ancestor: str, descendant: str) -> bool:
        """Return True iff ``ancestor`` is reachable from ``descendant``.

        Wraps ``git merge-base --is-ancestor``: exit 0 means ``ancestor``
        is an ancestor of ``descendant``. Any other exit (not-an-ancestor,
        unknown ref, git error) returns False — only exit 0 is a positive
        signal, so callers (notably the needs_human reconciliation pass)
        never act on ambiguity or missing refs.
        """
        result = self._git("merge-base", "--is-ancestor", ancestor, descendant)
        return result.returncode == 0

    @staticmethod
    def _parse_conflicting_files(porcelain_lines: List[str]) -> List[str]:
        """Extract blocking file paths from ``git status --porcelain``
        output.  Wraps the module-level helper so WorktreeManager
        callers can use method-style access in tests.
        """
        return _extract_conflicting_files(porcelain_lines)

    def _spec_lock(self, spec_id: str):
        """Return a file lock for merge serialization on a spec."""
        import filelock
        self.lock_dir.mkdir(parents=True, exist_ok=True)
        return filelock.FileLock(self.lock_dir / f"merge-{spec_id}.lock", timeout=120)

    def _git_config_lock(self):
        """Repo-wide lock for operations that write to .git/config.

        Git uses an exclusive lock on .git/config for upstream tracking writes.
        Concurrent ``git worktree add -b`` calls from parallel task execution
        race on this lock, causing "could not lock config file" errors.
        Serializing these calls through a filelock avoids the race.
        """
        import filelock
        self.lock_dir.mkdir(parents=True, exist_ok=True)
        return filelock.FileLock(self.lock_dir / "git-config.lock", timeout=120)

    # ------------------------------------------------------------------
    # Agent config propagation
    # ------------------------------------------------------------------

    def _copy_agent_configs(self, worktree_path: Path) -> None:
        """Copy agent/odin config files from project root into the worktree.

        Copies (not symlinks) each path in AGENT_CONFIG_PATHS so that
        ``load_config()`` and agent CLIs find their settings inside the
        worktree checkout. Best-effort: logs on failure, never raises.

        For directories that already exist (e.g. git checked out tracked
        files), merges missing files from the source so that untracked
        files like settings.local.json are not silently dropped.
        """
        for rel in AGENT_CONFIG_PATHS:
            src = self.project_root / rel
            dst = worktree_path / rel
            if not src.exists():
                continue
            try:
                if src.is_dir():
                    if dst.exists():
                        # Directory already exists (e.g. git created it with
                        # tracked files). Copy individual missing files so
                        # untracked files like settings.local.json get through.
                        for src_file in src.rglob("*"):
                            if not src_file.is_file():
                                continue
                            dst_file = dst / src_file.relative_to(src)
                            if dst_file.exists():
                                continue
                            dst_file.parent.mkdir(parents=True, exist_ok=True)
                            shutil.copy2(src_file, dst_file)
                            logger.debug("Merged config file %s → %s", src_file.relative_to(self.project_root), worktree_path)
                    else:
                        dst.parent.mkdir(parents=True, exist_ok=True)
                        shutil.copytree(src, dst)
                        logger.debug("Copied agent config %s → %s", rel, worktree_path)
                else:
                    if not dst.exists():
                        dst.parent.mkdir(parents=True, exist_ok=True)
                        shutil.copy2(src, dst)
                        logger.debug("Copied agent config %s → %s", rel, worktree_path)
            except OSError:
                logger.debug("Failed to copy agent config %s to worktree", rel)

    def _write_worktree_gitignore(self, worktree_path: Path) -> None:
        """Write agent config paths to git's ``info/exclude`` for the worktree.

        NEVER the tracked ``.gitignore``: mutating a tracked file leaves the
        worktree permanently dirty, and any task branch that also touches
        ``.gitignore`` then aborts its merge with would-be-overwritten
        (task 287). ``info/exclude`` gives identical ignore semantics with
        zero footprint in the tree. ``_GITIGNORE_MARKER`` keeps it
        idempotent — the exclude file is shared across worktrees of the
        repo, which is fine: the patterns are root-anchored and identical
        for every odin worktree.
        """
        try:
            result = subprocess.run(
                ["git", "rev-parse", "--git-path", "info/exclude"],
                cwd=worktree_path, capture_output=True, text=True, check=True,
            )
            exclude_path = Path(result.stdout.strip())
            if not exclude_path.is_absolute():
                exclude_path = worktree_path / exclude_path
            exclude_path.parent.mkdir(parents=True, exist_ok=True)
            existing = exclude_path.read_text() if exclude_path.exists() else ""
            if _GITIGNORE_MARKER in existing:
                return
            lines = [
                "",
                _GITIGNORE_MARKER,
                *(f"/{p}" for p in _WORKTREE_GITIGNORE_PATHS),
                "",
            ]
            with open(exclude_path, "a") as f:
                f.write("\n".join(lines))
            logger.debug("Wrote agent config excludes for %s", worktree_path)
        except (OSError, subprocess.CalledProcessError):
            logger.debug("Failed to write info/exclude for %s", worktree_path)

    def _clean_untracked_agent_configs(self, worktree_path: Path) -> None:
        """Remove untracked agent configs before merge to prevent conflicts.

        Only removes files/dirs that are NOT tracked by git (i.e. our copies).
        Also removes .gitignore if it contains our marker and is untracked.
        Walks ``AGENT_CONFIG_PATHS`` (the same list ``_copy_agent_configs``
        uses) so every copied file is covered.  Glob patterns (``*.orig``)
        are skipped here — they're handled by the worktree ``.gitignore``
        and the auto-commit reset.
        """
        paths_to_check: List[str] = [
            p for p in AGENT_CONFIG_PATHS if "*" not in p and "?" not in p
        ] + [".gitignore"]
        for rel in paths_to_check:
            target = worktree_path / rel
            if not target.exists():
                continue
            # Check if tracked
            check = self._git(
                "ls-files", "--error-unmatch", rel, cwd=worktree_path,
            )
            if check.returncode == 0:
                # Tracked by git — leave it alone
                continue
            # For .gitignore, only remove if it has our marker
            if rel == ".gitignore":
                content = target.read_text()
                if _GITIGNORE_MARKER not in content:
                    continue
            try:
                if target.is_dir():
                    shutil.rmtree(target)
                else:
                    target.unlink()
                logger.debug("Cleaned untracked %s from %s", rel, worktree_path)
            except OSError:
                logger.debug("Failed to clean %s from %s", rel, worktree_path)

    # ------------------------------------------------------------------
    # Spec branch
    # ------------------------------------------------------------------

    def create_spec_branch(self, spec_id: str, base_branch: str = "main") -> str:
        """Create spec/<spec_id> from base_branch. Returns branch name.

        Idempotent: if the branch already exists, returns its name.
        """
        branch = f"spec/{spec_id}"
        if self._branch_exists(branch):
            logger.info("Spec branch %s already exists, skipping creation", branch)
            return branch

        # Try to fetch latest from remote (best-effort)
        self._git("fetch", "origin", base_branch)

        # Check if the repo has any commits at all
        head_check = self._git("rev-parse", "HEAD")
        if head_check.returncode != 0:
            # Empty repo — create an initial commit so branches can exist
            logger.info("Empty repo detected, creating initial commit for worktree isolation")
            self._git("commit", "--allow-empty", "-m", "Initial commit (odin worktree setup)")

        # Create branch from the base. Prefer origin/<base> if it exists,
        # otherwise fall back to local <base>, then current HEAD.
        ref_check = self._git("rev-parse", "--verify", f"origin/{base_branch}")
        if ref_check.returncode == 0:
            base_ref = f"origin/{base_branch}"
        else:
            local_check = self._git("rev-parse", "--verify", base_branch)
            if local_check.returncode == 0:
                base_ref = base_branch
            else:
                # base_branch doesn't exist (e.g. config says "main" but repo has "master")
                base_ref = "HEAD"
                logger.warning("Base branch %s not found, using HEAD", base_branch)

        result = self._git("branch", branch, base_ref)
        if result.returncode != 0:
            # Parallel dispatch: another task may have created the branch
            # between our existence check and this call — losing that race
            # is success, not failure (F51).
            if self._branch_exists(branch):
                logger.info("Spec branch %s created concurrently by another task", branch)
                return branch
            raise RuntimeError(f"Failed to create spec branch {branch}: {result.stderr}")

        # Push to remote (best-effort — local-first)
        push = self._git("push", "-u", "origin", branch)
        if push.returncode != 0:
            logger.warning("Failed to push spec branch %s to remote: %s", branch, push.stderr.strip())

        logger.info("Created spec branch: %s from %s", branch, base_ref)
        return branch

    # ------------------------------------------------------------------
    # Spec worktree
    # ------------------------------------------------------------------

    def create_spec_worktree(
        self,
        spec_id: str,
        post_hooks: Optional[List[str]] = None,
        symlinks: Optional[List[str]] = None,
    ) -> Path:
        """Create a worktree for the spec branch itself.

        Lives at {worktree_base}/{spec_id}/_spec — the _spec subdirectory
        won't conflict with numeric task IDs.

        Idempotent: if the worktree already exists, returns its path.
        """
        spec_branch = f"spec/{spec_id}"
        worktree_path = self.worktree_base / spec_id / "_spec"

        if worktree_path.exists() and (worktree_path / ".git").exists():
            logger.info("Spec worktree already exists at %s, skipping creation", worktree_path)
            self._copy_agent_configs(worktree_path)
            return worktree_path

        # Clean up stale directory (exists but no .git — e.g. previous failed attempt)
        if worktree_path.exists():
            self._git("worktree", "remove", "--force", str(worktree_path))
            if worktree_path.exists():
                shutil.rmtree(worktree_path, ignore_errors=True)

        worktree_path.parent.mkdir(parents=True, exist_ok=True)

        result = self._git("worktree", "add", str(worktree_path), spec_branch)
        if result.returncode != 0:
            raise RuntimeError(
                f"Failed to create spec worktree for {spec_id}: {result.stderr}"
            )

        # Propagate agent/odin configs so CLIs find their settings
        self._copy_agent_configs(worktree_path)
        self._write_worktree_gitignore(worktree_path)

        # Create symlinks from project root (best-effort)
        for rel_path in (symlinks or []):
            src = self.project_root / rel_path
            dst = worktree_path / rel_path
            if src.exists() and not dst.exists():
                dst.parent.mkdir(parents=True, exist_ok=True)
                try:
                    dst.symlink_to(src)
                except OSError:
                    logger.warning("Failed to symlink %s -> %s", dst, src)

        # Run post-create hooks (best-effort)
        for hook_cmd in (post_hooks or []):
            try:
                subprocess.run(
                    hook_cmd,
                    shell=True,
                    cwd=worktree_path,
                    timeout=120,
                    capture_output=True,
                )
            except Exception:
                logger.warning("Post-create hook failed in %s: %s", worktree_path, hook_cmd)

        logger.info("Created spec worktree: %s (branch=%s)", worktree_path, spec_branch)
        return worktree_path

    def update_spec_worktree(self, spec_id: str) -> None:
        """Update the spec worktree to reflect the latest spec branch state.

        Called after a task merge updates the spec branch. Runs
        git reset --hard to pick up the new merge commit.

        Best-effort: logs a warning on failure, never raises.
        """
        worktree_path = self.worktree_base / spec_id / "_spec"
        if not worktree_path.exists():
            logger.debug("No spec worktree at %s, skipping update", worktree_path)
            return

        spec_branch = f"spec/{spec_id}"
        result = self._git("reset", "--hard", spec_branch, cwd=worktree_path)
        if result.returncode != 0:
            logger.warning(
                "Failed to update spec worktree at %s: %s",
                worktree_path, result.stderr.strip(),
            )
        else:
            logger.info("Updated spec worktree at %s to latest %s", worktree_path, spec_branch)

    # ------------------------------------------------------------------
    # Task worktree
    # ------------------------------------------------------------------

    def create_task_worktree(
        self,
        spec_id: str,
        task_id: str,
        post_hooks: Optional[List[str]] = None,
        symlinks: Optional[List[str]] = None,
    ) -> Path:
        """Create a worktree for a task, branched from the spec branch.

        Idempotent: if the worktree already exists, returns its path.
        """
        spec_branch = f"spec/{spec_id}"
        task_branch = f"task/{spec_id}/{task_id}"
        worktree_path = self.worktree_base / spec_id / str(task_id)

        # If worktree already exists, return it
        if worktree_path.exists() and (worktree_path / ".git").exists():
            logger.info("Worktree already exists at %s, skipping creation", worktree_path)
            # A worktree left half-provisioned by a crashed run may be
            # missing agent configs (notably .odin/config.yaml).  Re-run
            # the copy so load_config() finds its settings instead of
            # falling back to defaults and masking a real failure as a
            # resolver error (task #339).  Idempotent: only copies files
            # that don't already exist — never overwrites.
            self._copy_agent_configs(worktree_path)
            return worktree_path

        # Clean up stale directory (exists but no .git — e.g. a previous
        # failed attempt left a partial worktree).  Without this,
        # ``git worktree add`` fails with "already exists" on retry
        # (task 236).
        if worktree_path.exists():
            self._git("worktree", "remove", "--force", str(worktree_path))
            if worktree_path.exists():
                shutil.rmtree(worktree_path, ignore_errors=True)

        # Ensure spec branch is up-to-date (picks up merged upstream work)
        self._git("fetch", "origin", spec_branch)

        # Prefer the remote tracking ref if available
        ref_check = self._git("rev-parse", "--verify", f"origin/{spec_branch}")
        base_ref = f"origin/{spec_branch}" if ref_check.returncode == 0 else spec_branch

        # Create parent directory
        worktree_path.parent.mkdir(parents=True, exist_ok=True)

        # Serialize worktree creation: ``git worktree add -b`` from a remote
        # tracking ref writes upstream config to .git/config. Concurrent calls
        # race on git's internal config lock and fail with "could not lock
        # config file .git/config: File exists".
        with self._git_config_lock():
            # If the task branch already exists (e.g., from a previous failed attempt),
            # create worktree from the existing branch
            if self._branch_exists(task_branch):
                result = self._git("worktree", "add", str(worktree_path), task_branch)
            else:
                result = self._git(
                    "worktree", "add",
                    "-b", task_branch,
                    str(worktree_path),
                    base_ref,
                )

        if result.returncode != 0:
            raise RuntimeError(
                f"Failed to create worktree for task {task_id}: {result.stderr}"
            )

        # Propagate agent/odin configs so CLIs find their settings
        self._copy_agent_configs(worktree_path)
        self._write_worktree_gitignore(worktree_path)

        # Create symlinks from project root (best-effort)
        for rel_path in (symlinks or []):
            src = self.project_root / rel_path
            dst = worktree_path / rel_path
            if src.exists() and not dst.exists():
                dst.parent.mkdir(parents=True, exist_ok=True)
                try:
                    dst.symlink_to(src)
                except OSError:
                    logger.warning("Failed to symlink %s -> %s", dst, src)

        # Run post-create hooks (best-effort)
        for hook_cmd in (post_hooks or []):
            try:
                subprocess.run(
                    hook_cmd,
                    shell=True,
                    cwd=worktree_path,
                    timeout=120,
                    capture_output=True,
                )
            except Exception:
                logger.warning("Post-create hook failed in %s: %s", worktree_path, hook_cmd)

        logger.info("Created task worktree: %s (branch=%s)", worktree_path, task_branch)
        return worktree_path

    def get_worktree_path(self, spec_id: str, task_id: str) -> Path:
        """Return the path where a task's worktree would be."""
        return self.worktree_base / spec_id / str(task_id)

    # ------------------------------------------------------------------
    # Merge
    # ------------------------------------------------------------------

    def _auto_commit_worktree(self, spec_id: str, task_id: str, task_title: str = "") -> AutoCommitResult:
        """Commit any uncommitted changes in a task worktree before merging.

        Safety net for agents that write files but forget to git commit.

        Defence-in-depth against merge-time auto-commit pollution.  A
        stale ``.gitignore`` (one missing ``.venv*/``) lets
        ``git add -A`` drag an entire venv into the task branch — a real
        incident swept 4,738 files through every later merge.  Three
        layers, each independent of ``.gitignore``:

        1. **Generated-path reset** — unstages harness/MCP configs and
           worktree-local runtime paths (existing F24 guard).
        2. **Pollution blocklist** — unstages venv markers
           (``pyvenv.cfg`` roots, ``.venv*``, ``venv``), ``node_modules``,
           ``site-packages``, ``__pycache__`` at any depth.
        3. **Bulk-add guard** — if more than
           ``_AUTO_COMMIT_MAX_NEW_FILES`` NEW untracked files would be
           committed, refuses the bulk and commits only tracked
           modifications, catching pollution the blocklist doesn't name.

        Every exclusion is logged at WARNING level and reported in the
        returned :class:`AutoCommitResult` — never silent.

        Returns an ``AutoCommitResult`` (truthy iff a commit was created).
        """
        worktree_path = self.get_worktree_path(spec_id, task_id)
        if not worktree_path.exists():
            return AutoCommitResult()

        # Check for any changes (staged, unstaged, or untracked)
        status = self._git("status", "--porcelain", cwd=worktree_path)
        if not status.stdout.strip():
            return AutoCommitResult()

        logger.warning(
            "Task %s has uncommitted changes in worktree — auto-committing",
            task_id,
        )

        # Stage everything EXCEPT .proof/ — pathspec exclude is the
        # primary mechanism so proof artifacts are never in the index.
        # The reset below (Layer 1) is defence-in-depth for anything the
        # pathspec might miss.  An agent must never be able to lose a
        # task because the harness swept .proof/ into a commit.
        self._git("add", "-A", ".", ":(exclude).proof", cwd=worktree_path)

        # Layer 1 — unstage every generated/runtime path that must never
        # be committed.  Single source of truth derived from the harness/
        # MCP config writers plus worktree-local runtime paths.
        reset_args: List[str] = [
            "--",
            ".gitignore",
            *HARNESS_GENERATED_PATHS,
            *_WORKTREE_LOCAL_PATHS,
        ]
        self._git("reset", *reset_args, cwd=worktree_path)

        # Snapshot what remains staged after layer 1.
        cached = self._git("diff", "--cached", "--name-only", cwd=worktree_path)
        staged_paths = [p for p in cached.stdout.splitlines() if p.strip()]
        if not staged_paths:
            return AutoCommitResult()

        # Layer 2 — pollution blocklist.  Detect venv roots via the
        # ``pyvenv.cfg`` marker (catches non-standard names like ``env/``),
        # then unstage every staged file that is venv/build pollution.
        venv_roots = _find_venv_roots(staged_paths)
        blocklisted = [p for p in staged_paths if _is_pollution_path(p, venv_roots)]
        for i in range(0, len(blocklisted), _RESET_BATCH_SIZE):
            batch = blocklisted[i : i + _RESET_BATCH_SIZE]
            self._git("reset", "--", *batch, cwd=worktree_path)

        # Layer 3 — bulk-add guard.  Distinguish NEW files (status ``A``)
        # from tracked modifications; if there are too many new ones,
        # unstage them all and keep only the tracked modifications.
        cached_ns = self._git("diff", "--cached", "--name-status", cwd=worktree_path)
        new_files: List[str] = []
        for line in cached_ns.stdout.splitlines():
            if not line.strip():
                continue
            code = line[0]
            if code != "A":
                continue
            # Format: "<status>\t<path>" (renames have extra tabs; rare here).
            new_files.append(line.split("\t", 1)[1] if "\t" in line else line[2:])
        skipped_bulk = 0
        if len(new_files) > _AUTO_COMMIT_MAX_NEW_FILES:
            for i in range(0, len(new_files), _RESET_BATCH_SIZE):
                batch = new_files[i : i + _RESET_BATCH_SIZE]
                self._git("reset", "--", *batch, cwd=worktree_path)
            skipped_bulk = len(new_files)

        result = AutoCommitResult(
            skipped_blocklist=len(blocklisted),
            skipped_bulk=skipped_bulk,
        )

        # If nothing is left staged after all guards, bail out — but
        # report the exclusions loudly so the operator sees pollution
        # was refused even when no real work accompanied it.
        staged = self._git("diff", "--cached", "--name-only", cwd=worktree_path)
        if not staged.stdout.strip():
            if result.skipped:
                logger.warning(
                    "Auto-commit for task %s excluded %d file(s) and no "
                    "tracked modifications remained — nothing committed. %s",
                    task_id, result.skipped, result.summary,
                )
            return result

        msg = f"Auto-commit task {task_id}: {task_title}" if task_title else f"Auto-commit task {task_id}"
        msg += _provenance_trailers(spec_id, task_id)
        commit = self._git("commit", "-m", msg, cwd=worktree_path)
        if commit.returncode != 0:
            logger.warning("Auto-commit failed for task %s: %s", task_id, commit.stderr.strip())
            return result

        result.committed = True
        if result.skipped:
            logger.warning(
                "Auto-committed task %s with %d exclusion(s): %s",
                task_id, result.skipped, result.summary,
            )
        else:
            logger.info("Auto-committed uncommitted work for task %s", task_id)
        return result

    def merge_task_into_spec(
        self,
        spec_id: str,
        task_id: str,
        task_title: str = "",
        attempt_resolution: bool = False,
        resolution_guidance: str = "",
    ) -> MergeResult:
        """Merge a task branch into the spec branch.

        Auto-commits any uncommitted work in the task worktree first,
        then uses a file lock to serialize merges within the same spec.

        When ``attempt_resolution`` is True, mechanical conflicts
        (generated agent configs) are auto-resolved by the merge agent
        instead of leaving the task stuck.  See :mod:`odin.merge_agent`.

        ``resolution_guidance`` is a human's free-text reply to a prior
        ambiguous-conflict question — when set, it's applied to any
        ambiguous conflicts instead of escalating unconditionally
        (:func:`odin.merge_agent.resolve_ambiguous_with_guidance`).
        """
        spec_branch = f"spec/{spec_id}"
        task_branch = f"task/{spec_id}/{task_id}"

        if not self._branch_exists(task_branch):
            return MergeResult(success=False, error=f"Task branch {task_branch} does not exist")

        # Safety net: commit any uncommitted work before merging
        self._auto_commit_worktree(spec_id, task_id, task_title)

        lock = self._spec_lock(spec_id)
        try:
            with lock:
                return self._do_merge(
                    spec_branch, task_branch, task_id, task_title,
                    attempt_resolution=attempt_resolution,
                    task_brief=task_title,
                    resolution_guidance=resolution_guidance,
                )
        except Exception as exc:
            logger.exception("Merge failed for task %s into spec %s", task_id, spec_id)
            return MergeResult(success=False, error=str(exc))

    def _do_merge(
        self,
        spec_branch: str,
        task_branch: str,
        task_id: str,
        task_title: str,
        attempt_resolution: bool = False,
        task_brief: str = "",
        resolution_guidance: str = "",
    ) -> MergeResult:
        """Perform the actual merge (called under lock).

        Prefers the _spec worktree if it exists (the spec branch is already
        checked out there). Falls back to creating a temporary merge worktree
        for specs that predate the _spec worktree feature.
        """
        spec_id = spec_branch.removeprefix("spec/")
        spec_wt = self.worktree_base / spec_id / "_spec"
        use_spec_wt = spec_wt.exists() and (spec_wt / ".git").exists()

        if use_spec_wt:
            return self._merge_in_worktree(
                spec_wt, spec_branch, task_branch, task_id, task_title,
                attempt_resolution=attempt_resolution,
                task_brief=task_brief,
                resolution_guidance=resolution_guidance,
            )

        # Fallback: create a temporary merge worktree (older specs without _spec)
        merge_wt = self.worktree_base / "_merge" / f"spec_{spec_id}"
        if merge_wt.exists():
            self._git("worktree", "remove", "--force", str(merge_wt))

        try:
            merge_wt.parent.mkdir(parents=True, exist_ok=True)
            result = self._git("worktree", "add", str(merge_wt), spec_branch)
            if result.returncode != 0:
                return MergeResult(
                    success=False,
                    error=f"worktree add failed: {result.stderr}",
                )
            return self._merge_in_worktree(
                merge_wt, spec_branch, task_branch, task_id, task_title,
                attempt_resolution=attempt_resolution,
                task_brief=task_brief,
                resolution_guidance=resolution_guidance,
            )
        finally:
            if merge_wt.exists():
                self._git("worktree", "remove", "--force", str(merge_wt))

    def _strip_proof_from_merge_result(self, worktree: Path) -> bool:
        """Remove ``.proof/`` from the merge commit so it never reaches the spec branch.

        Agents write ``.proof/task-<id>/`` as per-task evidence.  It belongs on
        the task board (uploaded as attachments), not in the
        shared spec-branch git history.  The merge ``--no-ff`` is the single
        choke point where all task-branch content enters the spec branch, so
        stripping here covers both committed and uncommitted ``.proof/``
        regardless of how it arrived on the task branch — the mechanism
        cannot half-apply.

        ``git rm -r --cached`` removes ``.proof/`` from the index while
        leaving the working-tree files intact (the proof uploader reads them
        from the task worktree on disk).  ``--ignore-unmatch`` makes the call
        a no-op when ``.proof/`` is absent, so tasks with no proof files are
        unaffected.
        """
        rm = self._git(
            "rm", "-r", "--cached", "--ignore-unmatch", ".proof", cwd=worktree,
        )
        if rm.returncode != 0:
            logger.warning("Failed to strip .proof/ from merge result: %s", rm.stderr.strip())
            return False
        if not rm.stdout.strip():
            return False
        amend = self._git("commit", "--amend", "--no-edit", cwd=worktree)
        if amend.returncode != 0:
            logger.warning(
                "Failed to amend merge commit after .proof/ strip: %s",
                amend.stderr.strip(),
            )
            return False
        logger.info("Stripped .proof/ from merge result before push")
        return True

    def _changed_paths_since(self, worktree: Path, since_ref: str) -> List[str]:
        """List paths changed by ``since_ref..HEAD`` — added, copied,
        modified, renamed, or type-changed (NOT deleted; the gate
        ignores missing files anyway, but excluding them here keeps
        the result list lean and the contract explicit).

        Used by the post-merge safety gate (task 338) so it only
        inspects files the merge commit actually touched.
        """
        result = self._git(
            "diff", "--name-only", "--diff-filter=ACMRT",
            since_ref, "HEAD", cwd=worktree,
        )
        if result.returncode != 0:
            logger.warning(
                "Post-merge gate: failed to list changed paths: %s",
                result.stderr.strip(),
            )
            return []
        return [line for line in result.stdout.splitlines() if line.strip()]

    def _run_post_merge_gate(
        self,
        worktree: Path,
        diff_stat: Optional[str],
        task_branch: str,
        spec_branch: str,
        task_id: str,
    ) -> List[Tuple[str, str, int]]:
        """Run the post-merge safety gate against the merge commit.

        Walks every path the merge commit added/copied/modified/
        renamed/type-changed; runs :func:`odin.merge_agent._check_post_merge_files`
        against them; returns the violation list (empty on clean).
        The actual merge commit reset is the caller's responsibility
        so this function stays pure — easier to test.
        """
        # Local import keeps the merge-agent dependency one-way:
        # worktree → merge_agent. Avoids an import cycle in test
        # contexts that stub one without the other.
        from odin.merge_agent import _check_post_merge_files

        paths = self._changed_paths_since(worktree, "HEAD~1")
        if not paths:
            return []
        violations = _check_post_merge_files(worktree, paths)
        if violations:
            logger.warning(
                "Post-merge gate refused merge of %s into %s for task %s: %s",
                task_branch, spec_branch, task_id, violations,
            )
        return violations

    def _apply_merge_migration_fix(
        self,
        worktree: Path,
        conflict_check: "MigrationConflictCheck",
        spec_branch: str,
        task_id: str,
        diff_stat: Optional[str],
    ) -> Optional[MergeResult]:
        """Run the bounded ``makemigrations --merge`` fix for a migration
        leaf collision and fold the new migration into the merge commit.

        Returns a successful ``MergeResult`` when the graph is linear after
        the fix, or ``None`` when it fails (caller parks the task for a
        human).  ``--noinput`` makes Django 5.x proceed non-interactively:
        it swaps in ``MigrationQuestioner(defaults={"ask_merge": True})``
        which auto-confirms the merge.

        Called automatically by the merge gate whenever a leaf collision is
        detected (no human in the loop): ``makemigrations --merge`` creates
        a NEW migration file that Django generates deterministically — it
        never edits or renames existing files — so it is safe to run without
        confirmation.  Reserving distinct numeric prefixes at dispatch does
        not prevent leaf collisions (two parallel migrations always yield two
        leaves regardless of prefix), so this is the single mechanism.
        """
        backend = worktree / _DJANGO_BACKEND_REL_PATH
        merge_run = subprocess.run(
            ["python3", "manage.py", "makemigrations", "--merge", "--noinput"],
            cwd=str(backend),
            capture_output=True,
            text=True,
            timeout=60,
        )
        if merge_run.returncode != 0:
            logger.warning(
                "makemigrations --merge failed in %s: %s",
                backend, (merge_run.stderr or merge_run.stdout).strip(),
            )
            return None

        # Find the new untracked migration file(s) Django just wrote.
        status = self._git("status", "--porcelain", cwd=worktree)
        new_migrations = [
            line[3:].strip()
            for line in status.stdout.splitlines()
            if line.startswith("??") and "migrations/" in line and line[3:].strip().endswith(".py")
        ]
        if not new_migrations:
            logger.warning(
                "makemigrations --merge produced no new migration file in %s",
                worktree,
            )
            return None

        # Stage + amend so the merge migration travels inside the merge
        # commit (never a loose follow-up that a later reset would drop).
        for path in new_migrations:
            self._git("add", path, cwd=worktree)
        amend = self._git("commit", "--amend", "--no-edit", cwd=worktree)
        if amend.returncode != 0:
            logger.warning(
                "Failed to amend merge commit with merge migration: %s",
                amend.stderr.strip(),
            )
            return None

        # Re-check: the graph must now be linear before we push.
        recheck = _check_django_migration_conflicts(worktree)
        if recheck.has_conflict:
            logger.warning(
                "Migration collision persists after makemigrations --merge "
                "in %s: leaves=%s", worktree, recheck.leaves,
            )
            return None

        push = self._git("push", "origin", spec_branch, cwd=worktree)
        if push.returncode != 0:
            logger.warning(
                "Failed to push after merge-migration fix: %s",
                push.stderr.strip(),
            )

        leaves = list(conflict_check.leaves)
        rationale = (
            f"Created Django merge migration for leaf collision "
            f"({', '.join(leaves)}) via makemigrations --merge."
        )
        logger.info(
            "Migration leaf collision resolved via makemigrations --merge "
            "for task %s: %s", task_id, new_migrations,
        )
        return MergeResult(
            success=True,
            diff_stat=diff_stat,
            resolved_files=new_migrations,
            resolution_rationale=rationale,
        )

    def _merge_in_worktree(
        self,
        worktree: Path,
        spec_branch: str,
        task_branch: str,
        task_id: str,
        task_title: str,
        attempt_resolution: bool = False,
        task_brief: str = "",
        resolution_guidance: str = "",
    ) -> MergeResult:
        """Merge a task branch into the spec branch inside the given worktree.

        When ``attempt_resolution`` is True and a conflict occurs, the
        merge agent (:mod:`odin.merge_agent`) is invoked to resolve
        mechanical conflicts in-place.  Ambiguous conflicts abort the
        merge as before.
        """
        # Fetch and pull latest spec branch
        self._git("fetch", "origin", spec_branch)
        self._git("pull", "origin", spec_branch, cwd=worktree)

        # Capture diff stat before merge (spec..task shows what the task added)
        diff_stat_result = self._git(
            "diff", "--stat", f"{spec_branch}...{task_branch}", cwd=worktree,
        )
        diff_stat = diff_stat_result.stdout.strip() if diff_stat_result.returncode == 0 else None

        # Detect no-op: if the task branch has no commits beyond the spec branch,
        # there's nothing to merge. Don't lie about it.
        if not diff_stat:
            logger.warning(
                "Task %s has no changes vs spec branch — nothing to merge", task_id,
            )
            return MergeResult(success=True, noop=True)

        # Clean untracked agent configs to prevent merge conflicts
        self._clean_untracked_agent_configs(worktree)

        # Merge task branch
        spec_id = spec_branch.removeprefix("spec/")
        trailer = _provenance_trailers(spec_id, task_id)
        msg = f"Merge task {task_id}: {task_title}" if task_title else f"Merge task {task_id}"
        result = self._git("merge", "--no-ff", task_branch, "-m", msg + trailer, cwd=worktree)
        if result.returncode != 0:
            status = self._git("status", "--porcelain", cwd=worktree)
            status_lines = status.stdout.splitlines()
            conflicting_files = self._parse_conflicting_files(status_lines)
            has_conflicts = bool(conflicting_files)
            if has_conflicts:
                # Attempt merge-agent resolution if enabled
                if attempt_resolution:
                    from odin.merge_agent import resolve_conflicts_in_worktree

                    resolution = resolve_conflicts_in_worktree(
                        self, worktree, conflicting_files, task_brief,
                        resolution_guidance=resolution_guidance,
                        task_id=task_id,
                    )
                    if resolution.resolved:
                        # Complete the merge commit
                        commit_result = self._git(
                            "commit", "--no-edit", "-m",
                            msg + f"\n\nMerge agent resolution: {resolution.rationale}" + trailer,
                            cwd=worktree,
                        )
                        if commit_result.returncode == 0:
                            # Post-merge safety gate (task 338): the
                            # merge agent's resolution has landed;
                            # before pushing, run the cheapest honest
                            # checks against the files it touched.
                            # If markers / syntax errors survived, roll
                            # the commit back and refuse the merge so
                            # a broken state never reaches the spec
                            # branch.
                            gate_violations = self._run_post_merge_gate(
                                worktree, diff_stat, task_branch,
                                spec_branch, task_id,
                            )
                            if gate_violations:
                                reset = self._git("reset", "--hard", "HEAD~1", cwd=worktree)
                                if reset.returncode != 0:
                                    logger.error(
                                        "Failed to roll back merge commit "
                                        "after gate violation for task %s: %s",
                                        task_id, reset.stderr.strip(),
                                    )
                                logger.warning(
                                    "Post-merge gate refused merge of %s into "
                                    "%s for task %s: %d violation(s)",
                                    task_branch, spec_branch, task_id,
                                    len(gate_violations),
                                )
                                return MergeResult(
                                    success=False,
                                    conflict=True,
                                    needs_human=True,
                                    error=(
                                        f"Post-merge safety gate refused: "
                                        f"{len(gate_violations)} violation(s) "
                                        f"in resolved files"
                                    ),
                                    diff_stat=diff_stat,
                                    conflicting_files=list(
                                        {v[0] for v in gate_violations}
                                    ),
                                    resolved_files=[],
                                    resolution_rationale=resolution.rationale,
                                    gate_violations=list(gate_violations),
                                    agent_model=resolution.agent_model,
                                    token_usage=dict(resolution.token_usage),
                                )
                            self._strip_proof_from_merge_result(worktree)
                            push = self._git("push", "origin", spec_branch, cwd=worktree)
                            if push.returncode != 0:
                                logger.warning(
                                    "Failed to push spec branch after resolution: %s",
                                    push.stderr.strip(),
                                )
                            logger.info(
                                "Merge agent resolved %d conflict(s) for %s",
                                len(resolution.mechanical_files), task_id,
                            )
                            return MergeResult(
                                success=True,
                                diff_stat=diff_stat,
                                resolved_files=resolution.mechanical_files,
                                resolution_rationale=resolution.rationale,
                                agent_model=resolution.agent_model,
                                token_usage=dict(resolution.token_usage),
                            )
                        # Commit failed — fall through to abort
                        logger.warning(
                            "Merge-agent commit failed: %s",
                            commit_result.stderr.strip(),
                        )

                    if resolution.needs_human:
                        self._git("merge", "--abort", cwd=worktree)
                        return MergeResult(
                            success=False,
                            conflict=True,
                            error=f"Merge conflict (needs human): {resolution.rationale or 'ambiguous'}",
                            diff_stat=diff_stat,
                            conflicting_files=conflicting_files,
                            ambiguous_files=resolution.ambiguous_files,
                            resolved_files=[],
                            resolution_rationale=resolution.rationale,
                            needs_human=True,
                            conflict_hunks=dict(resolution.conflict_hunks),
                            file_resolutions={
                                k: dict(v) for k, v in resolution.file_resolutions.items()
                            },
                            spec_commit_messages={
                                k: list(v) for k, v in resolution.spec_commit_messages.items()
                            },
                            task_commit_messages={
                                k: list(v) for k, v in resolution.task_commit_messages.items()
                            },
                            agent_model=resolution.agent_model,
                            token_usage=dict(resolution.token_usage),
                        )

                # Standard abort path (resolution disabled or failed)
                self._git("merge", "--abort", cwd=worktree)
                return MergeResult(
                    success=False,
                    conflict=True,
                    error=f"Merge conflict: {result.stderr.strip()}",
                    diff_stat=diff_stat,
                    conflicting_files=conflicting_files,
                )
            # git reports conflict detail on stdout, not stderr — an empty
            # error string here is how task 284 vanished. Never empty.
            detail = (result.stderr or "").strip() or (result.stdout or "").strip() or "git merge aborted with no output"
            return MergeResult(success=False, error=f"merge failed: {detail}", diff_stat=diff_stat)

        # Strip per-task proof artifacts from the merge result.  .proof/
        # belongs on the task board (uploaded as attachments), not in the
        # spec-branch git history.
        self._strip_proof_from_merge_result(worktree)

        # Post-merge safety gate (task 338): cheapest honest checks on
        # the files the merge commit just landed — conflict markers and
        # Python syntax errors must not survive a merge into the shared
        # spec branch. Runs BEFORE the migration gate so a single broken
        # Python file is caught at the cheapest layer first; the
        # behavioral safety net (W5.12 spec-branch suite run) sits
        # behind both.
        gate_violations = self._run_post_merge_gate(
            worktree, diff_stat, task_branch, spec_branch, task_id,
        )
        if gate_violations:
            reset = self._git("reset", "--hard", "HEAD~1", cwd=worktree)
            if reset.returncode != 0:
                logger.error(
                    "Failed to roll back merge commit after gate violation "
                    "for task %s: %s",
                    task_id, reset.stderr.strip(),
                )
            logger.warning(
                "Post-merge gate refused merge of %s into %s for task %s: "
                "%d violation(s)",
                task_branch, spec_branch, task_id, len(gate_violations),
            )
            return MergeResult(
                success=False,
                conflict=True,
                needs_human=True,
                error=(
                    f"Post-merge safety gate refused: "
                    f"{len(gate_violations)} violation(s) in merged files"
                ),
                diff_stat=diff_stat,
                conflicting_files=list({v[0] for v in gate_violations}),
                gate_violations=list(gate_violations),
            )

        # Migration leaf-collision gate (wave-4 recurring class).
        # Two parallel task branches can each mint a migration with the
        # same numeric prefix (``0049_a.py``, ``0049_b.py``); ``git merge
        # --no-ff`` lands them side-by-side with no content overlap, so
        # git-level conflict detection never fires.  Django's
        # ``makemigrations --check`` is the only signal that the
        # migration graph now has two leaves with no merge migration —
        # check it here so the broken state never reaches the spec
        # branch (which would then poison every sibling's backend suite
        # until a human hand-adds a merge migration).
        conflict_check = _check_django_migration_conflicts(worktree)
        if conflict_check.has_conflict:
            error = _format_migration_conflict_error(
                conflict_check.leaves, conflict_check.app,
            )
            # Auto-resolve (wave-4/6/7/8 recurring class): run the bounded
            # ``makemigrations --merge`` fix WITHOUT waiting for a human.
            # Django creates a NEW merge migration deterministically — it
            # never edits or renames existing files — so this is safe to
            # do automatically, and it is the only mechanism that actually
            # prevents the collision.  Reserving distinct numeric prefixes
            # at dispatch does NOT help: two parallel migrations always
            # produce two leaf nodes regardless of their prefix number
            # (the collision is a graph-structure problem, not a numbering
            # one — verified empirically against Django 5.1).  The gate's
            # own re-check guarantees the graph is linear before the fix
            # is accepted; on any failure the merge parks for a human.
            fixed = self._apply_merge_migration_fix(
                worktree, conflict_check, spec_branch, task_id, diff_stat,
            )
            if fixed is not None:
                return fixed
            logger.warning(
                "Auto makemigrations --merge failed for task %s — "
                "parking for human intervention", task_id,
            )
            # Fallback: undo the local merge commit (spec branch was NOT
            # pushed), surface the collision as needs_human so the
            # reply-resume listener (tasks.signals) picks up a human's
            # guidance comment and re-attempts the bounded fix.
            reset = self._git("reset", "--hard", "HEAD~1", cwd=worktree)
            if reset.returncode != 0:
                logger.error(
                    "Failed to undo local merge after migration conflict "
                    "detection in %s: %s",
                    worktree, reset.stderr.strip(),
                )
            logger.warning(
                "Aborted merge of %s into %s due to migration leaf "
                "collision: %s",
                task_branch, spec_branch, conflict_check.leaves,
            )
            return MergeResult(
                success=False,
                conflict=True,
                needs_human=True,
                migration_conflict=True,
                error=error,
                diff_stat=diff_stat,
                conflicting_files=list(conflict_check.leaves),
            )

        # Push updated spec branch
        push = self._git("push", "origin", spec_branch, cwd=worktree)
        if push.returncode != 0:
            logger.warning("Failed to push spec branch after merge: %s", push.stderr.strip())

        logger.info("Merged %s into %s", task_branch, spec_branch)
        return MergeResult(success=True, diff_stat=diff_stat)

    # ------------------------------------------------------------------
    # Cleanup
    # ------------------------------------------------------------------

    def cleanup_task_worktree(self, spec_id: str, task_id: str) -> None:
        """Remove a task's worktree and delete its branch."""
        worktree_path = self.get_worktree_path(spec_id, task_id)
        task_branch = f"task/{spec_id}/{task_id}"

        if worktree_path.exists():
            result = self._git("worktree", "remove", "--force", str(worktree_path))
            if result.returncode != 0:
                logger.warning("Failed to remove worktree %s: %s", worktree_path, result.stderr.strip())

        if self._branch_exists(task_branch):
            self._git("branch", "-D", task_branch)

        logger.info("Cleaned up task worktree: %s", task_branch)

    def remove_task_worktree(self, spec_id: str, task_id: str) -> None:
        """Remove a task's worktree but preserve its branch.

        Used on task failure so committed work survives for recovery.
        """
        worktree_path = self.get_worktree_path(spec_id, task_id)
        task_branch = f"task/{spec_id}/{task_id}"

        if worktree_path.exists():
            result = self._git("worktree", "remove", "--force", str(worktree_path))
            if result.returncode != 0:
                logger.warning("Failed to remove worktree %s: %s", worktree_path, result.stderr.strip())

        logger.info("Removed task worktree (branch preserved): %s", task_branch)

    def finalize_spec(self, spec_id: str) -> None:
        """Clean up all worktrees for a spec. Does NOT merge to main (that's a PR)."""
        spec_dir = self.worktree_base / spec_id
        if spec_dir.exists():
            for task_dir in spec_dir.iterdir():
                if task_dir.is_dir():
                    self._git("worktree", "remove", "--force", str(task_dir))
            # Remove the spec directory itself if empty
            try:
                spec_dir.rmdir()
            except OSError:
                pass

        logger.info("Finalized spec %s: cleaned up worktrees", spec_id)

    def cleanup_all(self) -> None:
        """Remove all worktrees managed by this WorktreeManager."""
        if self.worktree_base.exists():
            for spec_dir in self.worktree_base.iterdir():
                if spec_dir.is_dir():
                    self.finalize_spec(spec_dir.name)

        # Prune stale worktree refs
        self._git("worktree", "prune")
        logger.info("Cleaned up all worktrees")

    # ------------------------------------------------------------------
    # PR creation
    # ------------------------------------------------------------------

    def create_spec_pr(
        self,
        spec_id: str,
        title: str,
        task_summaries: Optional[List[str]] = None,
    ) -> Optional[str]:
        """Create a GitHub PR from the spec branch to main.

        Requires `gh` CLI to be installed and authenticated.
        Returns the PR URL on success, None on failure.
        """
        spec_branch = f"spec/{spec_id}"

        # Build PR body
        body_lines = [f"## Spec: {title}", ""]
        if task_summaries:
            body_lines.append("### Tasks")
            for summary in task_summaries:
                body_lines.append(f"- {summary}")
            body_lines.append("")
        body_lines.append("Generated by `odin spec finalize`")
        body = "\n".join(body_lines)

        try:
            result = subprocess.run(
                [
                    "gh", "pr", "create",
                    "--base", "main",
                    "--head", spec_branch,
                    "--title", title,
                    "--body", body,
                ],
                cwd=self.project_root,
                capture_output=True,
                text=True,
                timeout=30,
            )
            if result.returncode == 0:
                pr_url = result.stdout.strip()
                logger.info("Created PR for spec %s: %s", spec_id, pr_url)
                return pr_url
            else:
                stderr = result.stderr.strip()
                logger.warning("Failed to create PR for spec %s: %s", spec_id, stderr)
                raise RuntimeError(stderr or "gh pr create failed with no output")
        except FileNotFoundError:
            logger.warning("gh CLI not found — cannot create PR for spec %s", spec_id)
            return None
        except Exception:
            logger.exception("Failed to create PR for spec %s", spec_id)
            return None
